### ISSUE TITLE
will this work with the one mix s platinum

### ISSUE THREAD

**Issue by digitxo** [balopez83/One-Mix-3-Hackintosh#2]
one mix 3s platinum

will it work?

**Comment by balopez83** [comment]
I am not sure though if it is using the same series processor then it likely will work. I would say try it and it likely will require minor tweaking if any to make it work. That said, if it is going to work it will currently only likely work with macOS Sierra as I have not yet even been able to get newer versions of macOS working yet on the 2s, 3, or 3s.

**Comment by wermy** [comment]
@balopez83 do you have yours back in working order, then?  Sorry, this is probably the wrong place to ask; but I've literally been checking this repo every day for updates.  😁

**Comment by balopez83** [comment]
@wermy  Yes, mine is back up and running. So far I have only just begun to pick up where I left off but lost some of the work I was working on when the computer crashed and so had to backtrack a little. as of now though I am only going to focus on Catalina rather than continuing to get Sierra or other older OS's functioning. I am waiting on some information from others regarding how they fixed some of the issues I am seeing and hopefully that will get this project closer to the finish line though not really sure how long this will take.
