### ISSUE TITLE
[Solved] Brightness screen control isn't working and not detect SSD on One Mix 3S

### ISSUE THREAD

**Issue by pokemonerdotcom** [balopez83/One-Mix-3-Hackintosh#3]
Thank you for your EFI, I actually installed into my USB 3.0! Well, I try to follow your tutorials but the SSD isn't detected from my One Mix 3s. When the installing is completed. I can come to Hackintosh with Bluetooth, Backlit keyboard and Trackpoint. But I can't control my Monitor brightness, it's always maximum and dry my battery so fast. 
I install it in Mac 10.12.6!
P/s: I actually made HackIONvme on with version 10.12.6 but the SSD isn't detected. 
Thank you for reading! Thanks for your EFI Again!

**Comment by pokemonerdotcom** [comment]
I can install into my SSD NVME! But Brightness screen control isn't working :(((

**Comment by pokemonerdotcom** [comment]
I actually fixed Brightness screen and everything is working! It's Working with One Mix 3S but you should make a patch for NVME to install into NVME! Solved!

**Comment by balopez83** [comment]
Hi @pokemonerdotcom ,  I am glad you were able to get the brightness working and I assume most everything else. I know you closed this but I wanted to ask some follow up questions and provide a couple recommendations because on my system I have full access to install on the internal NVME drive. 
What version of macOS are you using?
What brand NVME is in the 3s?
How are you partitioning the internal? And, are you dual booting and formatting the macOS space with NTFS prior to booting the macOS installer?

The installer & Clover require the NVME driver from the Clover installer in order to read any NVME SSD and my EFI currently loaded on Github does not have that in there as I was trying to keep it really clean and light. You will likely need to download the most recent Clover installer and check all the drivers currently included in my EFI but also add the NVME driver. Once you do that macOS should be able to "see" the drive as mine does. 

Let me know if that helps and if not I can try to assist further. Also keep in mind I am trying a complete rework of the EFI and so hopefully will get the system completely functional soon

**Comment by pokemonerdotcom** [comment]
Hi, Thank you for your efi because I can install mac os in my one mix 3s. So I am using Mac osx 10.12.6. About Nvme, it's native Nvme from one mix series, it's FORESEE 521 GB! Well, how I can install mac into my nvme. Hmm, so easy. I installed OS into a USB then, I used Carbon Copy Cloner to copy full os to NVME. It will copy EFI, recovery, ... all to NVME. Then, boot to your nvme and it's working! 
p/s 1: I made new aml for my nvme
p/s 2: The Audio is working so bad so I try to use AppleALC and try to find correctly audio device id :))) shit, It's just working with a center channel and right channel on speaker. On Headphone it's working perfectly!

**Comment by balopez83** [comment]
Ok, that was a pretty good way of getting it set up since it wasn't working with your NVME. I am surprised it didn't work with you drive to start since I have the same brand but just the 256GB version. I will look into it in the future but since you got your's working I will hold off on researching why it didn't work for you before. If you decide to start exploring Mojave or Catalina and discover a way to get it running with graphics before I do, please let me know.

**Comment by pokemonerdotcom** [comment]
Well, I can dual-boot Windows and Mac 10.12.6 on my NVME Now! New Update for One Mix 3s
